name: MDVHeadOres
version: 1.1.1
main: com.mdvcraft.headores.MDVHeadOresPlugin
api-version: '1.21'
author: MDVCraft
softdepend:
  - MMOItems
  - MMOCore
commands:
  mdvheadores:
    description: Comandos de MDVHeadOres.
    usage: /mdvheadores <reload|inspect|queue|generate>
    aliases:
      - mdvho
permissions:
  mdvheadores.admin:
    description: Permite administrar MDVHeadOres.
    default: op
